# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: blueprints.cloud.google.com/v1alpha1
kind: BlueprintMetadata
metadata:
  name: terraform-google-kubernetes-engine
  annotations:
    config.kubernetes.io/local-config: "true"
spec:
  title: Terraform Kubernetes Engine ASM Submodule
  source:
    repo: https://github.com/terraform-google-modules/terraform-google-kubernetes-engine
    sourceType: git
  version: 24.1.0
  actuationTool:
    type: Terraform
    version: '>= 0.14.0'
  examples:
  - name: deploy_service
    location: examples/deploy_service
  - name: disable_client_cert
    location: examples/disable_client_cert
  - name: node_pool
    location: examples/node_pool
  - name: node_pool_update_variant
    location: examples/node_pool_update_variant
  - name: node_pool_update_variant_beta
    location: examples/node_pool_update_variant_beta
  - name: node_pool_update_variant_public_beta
    location: examples/node_pool_update_variant_public_beta
  - name: private_zonal_with_networking
    location: examples/private_zonal_with_networking
  - name: regional_private_node_pool_oauth_scopes
    location: examples/regional_private_node_pool_oauth_scopes
  - name: safer_cluster
    location: examples/safer_cluster
  - name: safer_cluster_iap_bastion
    location: examples/safer_cluster_iap_bastion
  - name: shared_vpc
    location: examples/shared_vpc
  - name: simple_autopilot_private
    location: examples/simple_autopilot_private
  - name: simple_autopilot_public
    location: examples/simple_autopilot_public
  - name: simple_regional
    location: examples/simple_regional
  - name: simple_regional_beta
    location: examples/simple_regional_beta
  - name: simple_regional_private
    location: examples/simple_regional_private
  - name: simple_regional_private_beta
    location: examples/simple_regional_private_beta
  - name: simple_regional_with_kubeconfig
    location: examples/simple_regional_with_kubeconfig
  - name: simple_regional_with_networking
    location: examples/simple_regional_with_networking
  - name: simple_windows_node_pool
    location: examples/simple_windows_node_pool
  - name: simple_zonal_private
    location: examples/simple_zonal_private
  - name: simple_zonal_with_acm
    location: examples/simple_zonal_with_acm
  - name: simple_zonal_with_asm
    location: examples/simple_zonal_with_asm
  - name: simple_zonal_with_hub
    location: examples/simple_zonal_with_hub
  - name: simple_zonal_with_hub_kubeconfig
    location: examples/simple_zonal_with_hub_kubeconfig
  - name: stub_domains
    location: examples/stub_domains
  - name: stub_domains_private
    location: examples/stub_domains_private
  - name: stub_domains_upstream_nameservers
    location: examples/stub_domains_upstream_nameservers
  - name: terraform
    location: examples/acm-terraform-blog-part1/terraform
  - name: terraform
    location: examples/acm-terraform-blog-part2/terraform
  - name: terraform
    location: examples/acm-terraform-blog-part3/terraform
  - name: upstream_nameservers
    location: examples/upstream_nameservers
  - name: workload_identity
    location: examples/workload_identity
  - name: workload_metadata_config
    location: examples/workload_metadata_config
  variables:
  - name: channel
    description: The channel to use for this ASM installation.
    type: string
    default: ""
    required: false
  - name: cluster_location
    description: The cluster location for this ASM installation.
    type: string
    required: true
  - name: cluster_name
    description: The unique name to identify the cluster in ASM.
    type: string
    required: true
  - name: create_system_namespace
    description: Determines whether the module creates the istio-system namespace.
    type: bool
    default: true
    required: false
  - name: enable_cni
    description: Determines whether to enable CNI for this ASM installation. Required to use Managed Data Plane (MDP).
    type: bool
    default: false
    required: false
  - name: enable_fleet_registration
    description: Determines whether the module registers the cluster to the fleet.
    type: bool
    default: false
    required: false
  - name: enable_mesh_feature
    description: Determines whether the module enables the mesh feature on the fleet.
    type: bool
    default: false
    required: false
  - name: enable_vpc_sc
    description: Determines whether to enable VPC-SC for this ASM installation. For more information read https://cloud.google.com/service-mesh/docs/managed/vpc-sc
    type: bool
    default: false
    required: false
  - name: fleet_id
    description: The fleet to use for this ASM installation.
    type: string
    default: ""
    required: false
  - name: internal_ip
    description: Use internal ip for the cluster endpoint when running kubectl commands.
    type: bool
    default: false
    required: false
  - name: module_depends_on
    description: List of modules or resources this module depends on.  If multiple, all items must be the same type.
    type: list(any)
    default: []
    required: false
  - name: multicluster_mode
    description: '[Preview] Determines whether remote secrets should be autogenerated across fleet cluster.'
    type: string
    default: manual
    required: false
  - name: project_id
    description: The project in which the resource belongs.
    type: string
    required: true
  outputs:
  - name: revision_name
    description: The name of the installed managed ASM revision.
  - name: wait
    description: An output to use when depending on the ASM installation finishing.
  roles:
  - level: Project
    roles:
    - roles/cloudkms.admin
    - roles/cloudkms.cryptoKeyEncrypterDecrypter
    - roles/compute.networkAdmin
    - roles/compute.securityAdmin
    - roles/container.admin
    - roles/container.clusterAdmin
    - roles/container.developer
    - roles/iam.serviceAccountAdmin
    - roles/iam.serviceAccountUser
    - roles/compute.admin
    - roles/resourcemanager.projectIamAdmin
    - roles/composer.worker
    - roles/serviceusage.serviceUsageAdmin
    - roles/compute.osLogin
    - roles/compute.instanceAdmin
    - roles/iam.roleAdmin
    - roles/iap.admin
    - roles/gkehub.admin
  - level: Project
    roles:
    - roles/editor
    - roles/compute.admin
    - roles/container.admin
    - roles/resourcemanager.projectIamAdmin
    - roles/servicemanagement.admin
    - roles/serviceusage.serviceUsageAdmin
    - roles/iam.serviceAccountAdmin
    - roles/iam.serviceAccountKeyAdmin
    - roles/meshconfig.admin
    - roles/gkehub.admin
    - roles/privateca.admin
  services: []
